@base_url=http://localhost:8081
# @name auth

GET  {{base_url}}/tokenz


###
@token={{auth.response.body.$.token}}
###
POST {{base_url}}/todos
Content-Type: application/json
Authorization: Bearer {{token}}

{
     "text":"test01",
     "author":"Ss13"
}

###
POST {{base_url}}/todos
Content-Type: application/json
Authorization: Bearer {{token}}
transactionID: x123

{
     "text":"sleep"
}

###
GET {{base_url}}/todos
Content-Type: application/json
Authorization: Bearer {{token}}

###
DELETE  {{base_url}}/todos/1
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{base_url}}/todos
Content-Type: application/json

{
     "text":"test01",
     "author":"123"
}