.PHONY: build

build:
	go build \
		-ldflags "-X main.buildcommit='git rev-parse --short HEAD' \
		-X main.buildtime='date "+%Y-%m-%dT%H:%M:%S%Z:00"'" \
		-o app
image:
	docker build -t todo:test -f Dockerfile .

container:
	docker run -p:8080:8080 --env-file ./local.env graceful-shut-byhttp-serv